import { test, expect } from '@playwright/test';
const sample = async page => { await page.goto('/'); await page.getByRole('button',{name:'Explore sample analysis'}).click(); await page.getByRole('button',{name:'View recommendations'}).click(); };
const finish = async (page, generate=false) => {
  await page.getByRole('button',{name:'Revision Summary',exact:true}).click();
  await page.getByRole('checkbox').check();
  await page.getByRole('button',{name:'Accept Revision',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Revision accepted'})).toBeVisible();
  if(generate){const d=page.waitForEvent('download');await page.getByRole('button',{name:'Generate & finish'}).click();expect((await d).suggestedFilename()).toBe('GREEN-SPEC-proposed-specification.txt');}
  else await page.getByRole('button',{name:'Finish without document'}).click();
  await expect(page.getByRole('heading',{name:'Revision completed'})).toBeVisible();
};
test('two-level feedback preserves locked approvals and revision snapshots across reload', async ({page}) => {
  await sample(page);
  await page.locator('article').nth(0).getByRole('button',{name:'Accept',exact:true}).click();
  await expect(page.locator('article').first().getByRole('button',{name:'Reject',exact:true})).toBeDisabled();
  await page.locator('article').nth(1).getByRole('button',{name:'Reject',exact:true}).click();
  await page.getByLabel('Notes (optional)').fill('Avoid scarce suppliers');
  await page.getByRole('dialog').getByRole('button',{name:'Reject',exact:true}).click();
  await page.locator('article').nth(2).getByRole('button',{name:'Comment / Request adjustment'}).click();
  await page.getByLabel('Item feedback *').fill('Keep structural requirements unchanged');
  await page.getByRole('button',{name:'Save feedback'}).click();
  await page.getByRole('button',{name:'Revision Summary',exact:true}).click();
  await page.getByRole('button',{name:'Request Another Revision'}).click();
  await page.getByLabel('Revision feedback *').fill('Reduce cost more; keep increases below 2%');
  await page.getByRole('button',{name:'Regenerate revision'}).click();
  await page.getByRole('button',{name:'Home',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Finding greener possibilities'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Recommendations',exact:true})).toBeVisible({timeout:15000});
  await expect(page.locator('article').first().getByRole('button',{name:'Approved · Locked'})).toBeDisabled();
  await expect(page.locator('article').nth(1)).toContainText('Avoid scarce suppliers');
  await expect(page.locator('article').nth(2)).toContainText('Keep structural requirements unchanged');
  await page.getByRole('button',{name:'Revision History',exact:true}).click();
  await page.getByRole('button',{name:'View revision 1'}).click();
  await expect(page.getByRole('heading',{name:'Revision 1 · Read-only snapshot'})).toBeVisible();
  await expect(page.getByText('Reject reason: Too expensive · Avoid scarce suppliers')).toBeVisible();
  await page.reload();await page.getByRole('button',{name:'Open',exact:true}).click();
  await expect(page.getByText(/Revision 2/).first()).toBeVisible();
});
test('locked Option B detail agrees with cost/CO2 and optional output survives reload',async({page})=>{
  await sample(page);await page.locator('article').first().getByRole('button',{name:'Accept',exact:true}).click();
  await page.locator('article').first().getByRole('button',{name:'Compare',exact:true}).click();
  await expect(page.getByRole('button',{name:'Select Option B'})).toBeDisabled();
  await page.getByRole('button',{name:'Unlock to edit'}).click();await page.getByRole('button',{name:'Select Option B'}).click();
  await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:'Confirm and accept'}).click();
  await page.getByRole('button',{name:'← Details'}).click();
  await expect(page.getByRole('heading',{name:'Expected impact · Option B'})).toBeVisible();
  await expect(page.getByText(/−315 tCO₂e · Additional cost ฿250,000/)).toBeVisible();
  await page.getByRole('button',{name:'Recommendations',exact:true}).click();
  await page.getByLabel('Cost impact',{exact:true}).selectOption('increase');
  await expect(page.locator('article').filter({hasText:'Use a blended concrete mix'})).toContainText('Additional cost');
  await page.getByLabel('Cost impact',{exact:true}).selectOption('saving');
  await expect(page.locator('article').filter({hasText:'Use a blended concrete mix'})).toHaveCount(0);
  await page.getByRole('button',{name:'Clear filters',exact:true}).click();
  await finish(page);await expect(page.getByRole('button',{name:'Download revised document',exact:true})).toHaveCount(0);
  await page.reload();await page.getByRole('button',{name:'Open',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Revision completed'})).toBeVisible();
  await page.getByRole('button',{name:'Go to Project Management'}).click();
  await expect(page.getByRole('heading',{name:'Project management handoff'})).toBeVisible();
});
test('generated document downloads and final history is preserved',async({page})=>{
  await sample(page);await page.locator('article').first().getByRole('button',{name:'Accept',exact:true}).click();
  await finish(page,true);await expect(page.getByRole('button',{name:'Download revised document'})).toBeVisible();
  await page.getByRole('button',{name:'Revision History',exact:true}).click();await page.getByRole('button',{name:'View revision 1'}).click();
  await expect(page.getByText('Approved · Option A · Locked')).toBeVisible();
});
test('upload has no replace button, validation preserves files, add and remove work',async({page})=>{
  await sample(page);await page.getByRole('button',{name:'Documents',exact:true}).click();
  await expect(page.getByRole('button',{name:/Replace/})).toHaveCount(0);
  await page.getByLabel('Upload documents',{exact:true}).setInputFiles({name:'bad.exe',mimeType:'application/octet-stream',buffer:Buffer.from('bad')});
  await expect(page.getByRole('dialog')).toContainText('Unsupported file type');await page.getByRole('button',{name:'Close dialog'}).click();
  await expect(page.getByText('TOR.pdf',{exact:true})).toBeVisible();
  await page.getByLabel('Upload documents',{exact:true}).setInputFiles({name:'Replacement.pdf',mimeType:'application/pdf',buffer:Buffer.from('mock')});
  await expect(page.getByText('TOR.pdf',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Analyze project'})).toBeDisabled();
  await expect(page.getByRole('button',{name:'Analyze project'})).toBeEnabled();await page.getByRole('button',{name:'Remove Replacement.pdf'}).click();
  await expect(page.getByText('Replacement.pdf',{exact:true})).toHaveCount(0);
});
test('zero-change revision can finish and mobile summary remains within viewport',async({page})=>{
  await sample(page);await page.getByLabel('DEMO SCENARIO').selectOption('none');await page.getByRole('button',{name:'Documents',exact:true}).click();
  await page.getByRole('button',{name:'Analyze project'}).click();await expect(page.getByRole('heading',{name:'No recommendations found'})).toBeVisible({timeout:15000});
  await page.setViewportSize({width:390,height:844});await finish(page);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
